[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mjewelplot"
version = "0.1.0"
requires-python = ">= 3.8"
dependencies = [
    "argparse",
    "pandas >= 2.2.2",
    "matplotlib >= 3.9.2",
]

[project.scripts]
mjewelplot = "mjewelplot:main"